# Generated by Django 3.2.7 on 2021-10-03 10:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='abi',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
